name: CI

permissions:
  contents: read
  security-events: write

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      #after set up go mod tidy will recreate go.sum if needed
      - name: Create empty go.sum(temporarily)
        run: |
          if [ ! -f go.sum ]; then
            echo "go.sum not found â€” creating an empty one"
            touch go.sum
          fi

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: OSV scan (dependencies)
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.1
        with:
          scan-args: |
            -r .
            --format json
            --output osv-report.json
        continue-on-error: true

      - name: Show OSV report
        run: cat osv-report.json

      - name: Run build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Run Go fuzz tests (dynamic analysis)
        run: go test -fuzz=Fuzz -fuzztime=5s ./...

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v1.61.0

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run Gosec (as SAST)
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Trivy fs scan (SCA + Config scanning)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: vuln,secret,config
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Install Semgrep CLI
        run: pip install semgrep

      - name: Semgrep Scan(SAST) with SARIF creation
        run: |
          semgrep scan --config p/golang --config p/owasp-top-ten --sarif-output semgrep.sarif .
          echo "=== SEMGREP SARIF OUTPUT ==="
          cat semgrep.sarif

      - name: Initialize CodeQL(yes, it needs to be initialized)
        uses: github/codeql-action/init@v4
        with:
          languages: go

      - name: Upload Semgrep SARIF to GitHub Security Tab
        uses: github/codeql-action/upload-sarif@v4
        with:
          sarif_file: semgrep.sarif

      - name: Build Docker image
        run: docker build -t app-dummy .

      - name: Grype scan (container image)
        uses: anchore/scan-action@v3
        with:
          image: app-dummy
          fail-build: false     #just for learning project
          output-format: table

      - name: Trivy image scan (for container security)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-dummy
          scanners: vuln,secret,config
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Generate Syft SBOM (CycloneDX) by container image
        uses: anchore/sbom-action@v0.15.0
        with:
          #when messed up with version, set syft-version
          upload-artifact: false
          image: app-dummy
          format: cyclonedx-json
          output-file: sbom.json

      # --- Grype: CVE scan based on SBOM ---
      - name: Grype scan (SBOM)
        run: grype sbom:sbom.json -o table


      - name: Save SBOM artifact(in order to have possibility to download)
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Run tfsec (IaC scan)
        uses: aquasecurity/tfsec-action@v1.0.0
        with:
          working_directory: iac
          additional_args: --soft-fail
          version: v1.28.14

      - name: Run Checkov IaC scan(Not needed in other pojects, but it s learning project, with no prod)
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: iac
          quiet: false
          soft_fail: false





