name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod tidy

      - name: Run build
        run: go build -v ./...

      - name: Run tests
        run: go test -v ./...

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: v1.61.0

      - name: Run golangci-lint
        run: golangci-lint run

      - name: Run Gosec (as SAST)
        uses: securego/gosec@master
        with:
          args: ./...

      - name: Trivy fs scan (SCA + Config scanning)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: fs
          scanners: vuln,secret,config
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Build Docker image
        run: docker build -t app-dummy .

      - name: Trivy image scan (for container security)
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: app-dummy
          scanners: vuln,secret,config
          severity: HIGH,CRITICAL
          ignore-unfixed: true
          exit-code: 1

      - name: Generate Syft SBOM (CycloneDX) by container image
        uses: anchore/sbom-action@v0.15.0
        with:
          upload-artifact: false
          image: app-dummy
          format: cyclonedx-json
          output-file: sbom.json

      - name: Save SBOM artifact(in order to have possibility to download)
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.json

      - name: Run tfsec (IaC for security scan)
        uses: aquasecurity/tfsec-pr-commenter-action@v1.3.1
        with:
          tfsec_args: iac





